### ISSUE TITLE
Cijfers en Agenda

### ISSUE THREAD

**Issue by LimitedDani** [Magister-Android/magister-api#3]
Kun je me 1 keer goed uitleggen of een code geven waarmee ik cijfers ophaal en de agenda ophaal?

**Comment by maxverbeek** [comment]
``` java
// Inloggen
MagisterAPI api = new MagisterAPI("school", "gebruikersnaam", "wachtwoord");

// Dit is een lijst met alle cijfers
CijferList cijfers = api.getCijfers();

// CijferList extends ArrayList, dus je kunt er gewoon doorheen loopen. Het zelfde geldt voor AfspraakList.

for (Cijfer cijfer : cijfers) {
   System.out.println("Cijfer voor " + cijfer.Vak.Omschrijving + ": " + cijfer.CijferStr);
}

// Met een cijfer object geeft magister je helaas vrij weinig info. Daarom moet je extra informatie met een apart request ophalen. Dit kan als volgt:

// LET OP: Als je 80 cijfers hebt, voert deze code 80 HTTP requests uit. Dit kan dus heel erg traag zijn, en ik raad je sterk aan om dit te cachen.

Sessie mainSessie = api.getMainSessie();

for (Cijfer cijfer : cijfers) {
    cijfer.setInfo(mainSessie.getCijferInfo(cijfer));

    // Nu kun je ook bijvoorbeeld de weging van een cijfer zien:
    System.out.println(sprintf("Cijfer op %s: %s (%d keer)", cijfer.Vak.Omschrijving, cijfer.CijferStr, cijfer.info.Weging);
}

// Dit zijn de cijfers die je op het magister dashboard ziet als: recent toegevoegd. Hiermee is helaas vrij weinig te doen.
CijferList recentCijfers = api.getRecentCijfers();


// Agenda: hiervoor heb je minimaal 2 parameters nodig, van en tot. Deze geven aan van en tot wanneer de items moeten worden opgehaald.

DateTime van = Utils.now();
DateTime tot = van.plusDays(7);

// Je hebt ook nog een optionele parameter (default = false) die aangeeft of je uitgevallen afspraken erbij wilt zien.
boolean geenUitval = false;

AfspraakList afspraken = api.getAfspraken(van, tot, geenUitval);
```

Ik hoop dat het zo duidelijker is. Als je precies wilt weten welke informatie allemaal beschikbaar is, kijk dan naar de member variabelen in Cijfer.java of Afspraak.java.

**Comment by maxverbeek** [comment]
Mocht je een uitgebreider voorbeeld willen, dan kun je altijd naar onze android implementatie kijken.

[Dit](https://github.com/Magister-Android/Magister-Android/blob/master/app/src/main/java/eu/magisterapp/magisterapp/Storage/DataFixer.java) is het bestand waar we voornamelijk de informatie uit de API halen.

**Comment by LimitedDani** [comment]
Agenda werkt al nog 1 vraagje. Hoe haal je de cijfers per vak op?

**Comment by LimitedDani** [comment]
Dat je cijfers sorteert zegmaar

**Comment by maxverbeek** [comment]
Je kan ze niet per vak ophalen. Je kan ze wel allemaal tegelijk ophalen, en daarna in een array zetten.

``` java

CijferList cijfersVanMagister = ...

Map<Integer, CijferList> cijfers = new HashMap<>();

for (Cijfer cijfer : cijfersVanMagister) {
    int vakId = cijfer.Vak.Id; // Elk vak heeft een eigen Id, dit kun je dus gebruiken om dingen te groeperen.

    if (cijfers.get(vakId) == null) cijfers.put(vakId, new CijferList());

    cijfers.get(vakId).add(cijfer);
}
```

**Comment by ghost** [comment]
ik heb deze code: `import requests
session = requests.Session()
data = {'username': 'your_username', 'password': 'your_password'}
session.post('https://your_school.magister.net/api/sessies', data=data)
grades_url = 'https://your_school.magister.net/api/cijfers'
grades = session.get(grades_url).json()
for grade in grades:
    print(f'{grade["vak"]}: {grade["cijfer"]}')`
maar hij werkt niet bepaalt hij is in python hoe zou ik de api kunnen gebruiken?

**Comment by ghost** [comment]
ook zou ik graag de agenda willen kunnen zien hoe zou ik dat kunnen doen in python?
